<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <style>
        * { font-family: DejaVu Sans, sans-serif; }
        body { color: #292524; font-size: 11px; margin: 0; }
        h1 { font-size: 22px; margin: 0 0 2px; color: #1c1917; }
        .subtitle { color: #78716c; font-size: 12px; margin-bottom: 14px; }
        .summary { margin-bottom: 16px; font-size: 11px; color: #57534e; }
        .summary strong { color: #1c1917; }
        table { width: 100%; border-collapse: collapse; }
        th { text-align: left; border-bottom: 2px solid #e7e5e4; padding: 6px 8px; font-size: 10px; text-transform: uppercase; letter-spacing: .04em; color: #78716c; }
        td { border-bottom: 1px solid #f0eeec; padding: 6px 8px; }
        .muted { color: #a8a29e; }
        .pill { font-size: 10px; }
        .footer { margin-top: 24px; text-align: center; color: #a8a29e; font-size: 10px; }
    </style>
</head>
<body>
    <h1>{{ $wedding->name }} — Guest List</h1>
    <div class="subtitle">
        @if ($wedding->event_date){{ $wedding->event_date->format('l, F j, Y') }}@endif
    </div>

    <div class="summary">
        <strong>{{ $counts['total'] }}</strong> invited &middot;
        <strong>{{ $counts['attending'] }}</strong> attending &middot;
        <strong>{{ $counts['pending'] }}</strong> pending &middot;
        <strong>{{ $counts['declined'] }}</strong> declined
    </div>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>RSVP</th>
                <th>Meal</th>
                <th>Dietary notes</th>
                <th>Table</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($guests as $guest)
                <tr>
                    <td>{{ trim($guest->first_name.' '.$guest->last_name) }}</td>
                    <td class="pill">{{ $guest->rsvp_status->label() }}</td>
                    <td>{{ $guest->meal_choice ?: '—' }}</td>
                    <td>{{ $guest->dietary_notes ?: '' }}</td>
                    <td>{{ $guest->seatingTable?->name ?? '—' }}</td>
                </tr>
            @empty
                <tr><td colspan="5" class="muted">No guests yet.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">Generated by WedFlow Atelier</div>
</body>
</html>
