<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <style>
        * { font-family: DejaVu Sans, sans-serif; }
        body { color: #292524; font-size: 11px; margin: 0; }
        h1 { font-size: 22px; margin: 0 0 2px; color: #1c1917; }
        .subtitle { color: #78716c; font-size: 12px; margin-bottom: 18px; }
        h2 { font-size: 13px; color: #be123c; margin: 18px 0 8px; border-bottom: 1px solid #f0eeec; padding-bottom: 4px; }
        .event { padding: 6px 0; border-bottom: 1px solid #f7f5f4; }
        .time { font-weight: bold; color: #1c1917; width: 120px; display: inline-block; }
        .title { color: #1c1917; }
        .meta { color: #78716c; margin-top: 2px; margin-left: 120px; font-size: 10px; }
        .muted { color: #a8a29e; }
        .footer { margin-top: 24px; text-align: center; color: #a8a29e; font-size: 10px; }
    </style>
</head>
<body>
    <h1>{{ $wedding->name }} — Run of Show</h1>
    <div class="subtitle">
        @if ($wedding->event_date){{ $wedding->event_date->format('l, F j, Y') }}@endif
    </div>

    @forelse ($days as $date => $events)
        <h2>{{ \Illuminate\Support\Carbon::parse($date)->format('l, F j, Y') }}</h2>
        @foreach ($events as $event)
            <div class="event">
                <span class="time">{{ $event->starts_at->format('g:i A') }}@if ($event->ends_at)–{{ $event->ends_at->format('g:i A') }}@endif</span>
                <span class="title">{{ $event->title }}</span>
                @if ($event->location || $event->vendor || $event->notes)
                    <div class="meta">
                        @if ($event->location){{ $event->location }}@endif
                        @if ($event->vendor) &middot; {{ $event->vendor->name }}@endif
                        @if ($event->notes) &middot; {{ $event->notes }}@endif
                    </div>
                @endif
            </div>
        @endforeach
    @empty
        <p class="muted">No timeline events yet.</p>
    @endforelse

    <div class="footer">Generated by WedFlow Atelier</div>
</body>
</html>
